server:
  port: 17000
spring:
  redis:
    host: 81.71.36.134
    port: 6379
    password:
  application:
    name: docu-mem-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/docu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
management:
  endpoints:
    web:
      exposure:
        include: '*'
ribbon:
  ReadTimeout: 5000 #请求时间5秒
  ConnectTimeout: 5000 #连接时间5秒
feign:
  hystrix:
    enabled: true
